# -*- coding: utf-8 -*-
"""Hack4tkm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VivfvN7nd1OboI2NBMelOEby18pqRTiY
"""

import pandas as pd
import matplotlib_inline
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

""" 
  # Data
"""

file=pd.read_csv("/content/Hack4TKM - Sheet1 (2).csv")
print(file)

file.head()

plt.subplot(221)
plt.bar(file["Temperature"],file["Units"])
 
plt.xlabel("Temperature")
plt.ylabel("Units")
plt.grid(True)

plt.subplot(222)
plt.bar(file["Humidity"],file["Units"])
plt.xlabel("humidity") 
plt.ylabel("Units")
plt.title('variation with Humidity')
plt.grid(True)


plt.subplot(223)
plt.bar(file["Precipitation"],file["Units"])
plt.xlabel("Precipitation") 
plt.ylabel("Units")
plt.title('variation with precipitation')
plt.grid(True)

plt.subplot(224)
plt.bar(file["Type of Institution"],file["Units"])
plt.xlabel("Type of Institution") 
plt.ylabel("Units")
plt.title('variation with Institution')
plt.grid(True)

X=file[["Temperature","Humidity","cloudy","Precipitation","hours presented in house","no of people presente in house","Type of Institution"]]
 y=file["Units"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

regr = linear_model.LinearRegression()

regr.fit(X, y)

xc=regr.predict([[36,84,1,59,17,3,5]])

xc

regr.score(X_test,y_test)

"""# Random Forest"""

rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
 
rf.fit(X_train,y_train);

predictions = rf.predict( [[36,84,1,59,17,3,5]])
 
print(predictions)

rf.score(X_test,y_test)